feat: add docker-compose

diff --git a/Dockerfile-docs b/Dockerfile-docs
--- a/Dockerfile-docs
+++ b/Dockerfile-docs
@@ -1,12 +1,86 @@
-FROM node:16-alpine
-RUN apk add g++ make python3
+ARG NODE_VERSION=16
+ARG ALPINE_VERSION=3.15
 
-RUN mkdir -p /opt/app
-WORKDIR /opt/app
+# multi stage build
 
-COPY package.json .
-COPY yarn.lock .
+# Install dependencies only when needed
+FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS deps 
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat rsync
+WORKDIR /app
+RUN yarn global add turbo
 
+# turbo prune
+RUN turbo prune --scope=docs --docker
+
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
 RUN \
-  apk --no-cache add \
-  libc6-compat
+  if [ -f yarn.lock ]; then yarn; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+COPY .gitignore .gitignore
+COPY turbo.json turbo.json
+RUN --mount=type=bind,target=/docker-context \
+    rsync -amv --delete \
+          --exclude='node_modules' \
+          --exclude='*/node_modules' \
+          --include='package.json' \
+          --include='schema.prisma' \
+          --include='*/' --exclude='*' \
+          /docker-context/ /app/;
+
+
+ENV PRISMA_CLI_BINARY_TARGETS=linux-musl
+
+###################################################################
+# Stage 2: Build the app                                          #
+###################################################################
+
+# Rebuild the source code only when needed
+FROM node:16-alpine AS builder
+WORKDIR /app
+COPY --from=deps /app ./
+COPY . .
+ENV NODE_ENV=production
+ENV NEXTJS_IGNORE_ESLINT=1
+ENV NEXTJS_IGNORE_TYPECHECK=0
+
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+# ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN yarn build
+
+# If using npm comment out above and use below instead
+# RUN npm run build
+
+# Production image, copy all the files and run next
+FROM node:16-alpine AS runner
+WORKDIR /app
+
+ENV NODE_ENV production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/public ./public
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+
+EXPOSE 3000
+
+ENV PORT 3000
+
+CMD ["node", "server.js"]
